export enum StatusOrderDomainEnum {
    ORDER_STATUS_SEO_CREATE = 'SEO_CREATE_ORDER',
    ORDER_STATUS_CREATE = 'CREATE_ORDER',
    ORDER_STATUS_DONE = 'DONE_ORDER',
    ORDER_STATUS_CANCEL = 'CANCEL_ORDER',
    ORDER_STATUS_ASYNC = 'ASYNC_ORDER',
    // ORDER_STATUS_APPROVED = 'APPROVED_ORDER',
}
